### ISSUE TITLE
Prefetch not working?

### ISSUE THREAD

**Issue by homerjam** [nuxt-community/apollo-module#210]
### Version

[v4.0.0-rc.4](https://github.com/apollo-module/releases/tag/v4.0.0-rc.4)

### Reproduction link

[https://codesandbox.io/embed/vny6o5o1j3](https://codesandbox.io/embed/vny6o5o1j3)

### Steps to reproduce

Refresh the page and check the terminal/console

### What is expected ?

The expected result is that the allCars data is available in the created() hook

### What is actually happening?

The allCars data is undefined

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/apollo-module/issues/c193">#c193</a>)</em></sub></div>

**Comment by kieusonlam** [comment]
I think it's belong to `vue-apollo` https://github.com/Akryum/vue-apollo/blob/c466f9893fe34ef83503054cdd3e933778ca5f21/src/mixin.js#L159

Look like it's still loading on created hook.

**Comment by francoisp** [comment]
Nice work, nuxt-apollo! Hey I'm having a very similar issue with @nuxtjs/apollo@4.0.0-rc6. On SSR (triggered say by a page reload in incognito mode) the cookie is not passed to the node-fetch agent doing the apollo request. It's passed in the request that triggers the SSR, I stepped through the code. I've put 

credentials: 'include', 

about everywhere possible in nuxt.config.js(apollo node) for good measure. Is that by design? This would be when the apollo client is (created/recreated) SSR from what I understood stepping thru the code. I could not find where I would have the initiating req (which has the cookie) and the apollo client to set the header on this connection. Is this a design issue? Should SSR be invariant for caching reasons or something? ( I dont see the render being cached ...)

When I step thru the SSR in the above scenario, I see the cookie (I'm using express-session so in this case it's the connect.sid value that I'm after) in the request. 

in nuxtjs/apollo/templates/plugin.js I see that in the getAuth the token is extracted from the cookie. In the debugger I see in defaultGetAuth that the req has the cookie I’m looking for. I also see that there’s a function getToken that would returned a concatenated cookie that would have the session cookie, but it’s never called.

Any ideas?

 TIA!

**Comment by kieusonlam** [comment]
Close due to `vue-apollo` https://github.com/vuejs/vue-apollo/issues/623#issuecomment-544452874
