### ISSUE TITLE
ssr error "You must wrap the query string in a "gql" tag" when use option function

### ISSUE THREAD

**Issue by KosmyninOleksandr** [nuxt-community/apollo-module#32]
Issue https://github.com/nuxt-community/apollo-module/issues/19 was closed but I still get this error. 

here is example of my call, I need to use function "update" so metadata defined as a function

```javascript
import metadataGql from '#/apollo/queries/metadata'

export default {
  data () {
    return {}
  },
  apollo: {
    metadata () {
      return  {
        query: metadataGql,
        update (metadata) {
          return metadata
        },
      }
    },
  },
```

**Comment by dohomi** [comment]
@KosmyninOleksandr this issue has something to do with vue-apollo, not especially Nuxt module, if your query name differs: apollo[queryName] otherwise you need to use update function.
```
apollo:{
  allPages:{
    query: allPagesQuery => query allPages exist, then there is no warning/error
  }
}
``` 
The newest version of vue-apollo introduced now the `manual` mode, check it out here: https://github.com/Akryum/vue-apollo#advanced-options

With that there wont be an automatic property update. So as I don't know how your *gql file looks alike, make sure that the query name is uses as apollo[queryName] as well.

**Comment by alidcastano** [comment]
^ Btw, it could also be that you configure the query incorrectly. I encountered this error and just realized I had incorrectly put the `error` option outside of the query and accidently as a prop in the root `apollo` object
