### ISSUE TITLE
Response headers and request session are never accessible at the same time

### ISSUE THREAD

**Issue by samirph** [nuxt-community/apollo-module#47]
When I receive a response through apollo, I can access `response.headers.get('refreshToken')` to get my server token.

But it seems to be accessible on client-side only, I have to add 
```
if (process.browser) {
    response.headers.get('accessToken')
}
```
`req.session` however, seems to be accessible only on server-side. 
Is it not possible to store tokens received on `response.headers` inside `req.session`?

**Comment by samirph** [comment]
Maybe I'm doing something wrong.
I just want req.session to store the user token after login, so it is able to persist on page refresh and be accessible on page fetch method (like in here https://nuxtjs.org/api/pages-fetch/)

Couldn't figure out another way to check user authorization in protected pages before they are loaded and shown to the user.

**Comment by dohomi** [comment]
@samirph then use vuex and localstorage to persist the token. one question: do you develop an app where your have a user-login and then you want to submit the token for the grapql requests based on that token?

**Comment by samirph** [comment]
Yes, once the user logs in, his token will be sent along in every graphql request.

These nuxt docs recomend to use fetch for route authentication (https://nuxtjs.org/examples/auth-routes/), but localstorage and cookies don't seem to be accessible in that method. Even though vuex is accessible there, it doesn't persist, so even if the user has a valid token in localstorage, he would be redirected to the login page when directly accessing a page he should be allowed to access.

**Comment by dohomi** [comment]
be aware: if you have user-login to show authenticated pages, then don't make the mistake to persist that token on the server! otherwise all upcoming requests are permitted as well. Its crucial that every login attempt only happens on the client side, and only wired down via vuex to the server if needed. this is why in all fetch/async or plugins you can access the store state in the req property.

**Comment by samirph** [comment]
So you are saying I should directly store tokens on the client side when I get an apollo response?
And then, authentication can only be verified once the page is created and displayed to the user?

It is confusing, since this apollo-module docs tells me to get the token stored in the session like this
```
// auth token
  let token = ctx.isServer ? ctx.req.session : window.__NUXT__.state.session
```
And nuxt route auth example in the docs (https://nuxtjs.org/examples/auth-routes/) uses a middleware for that, which is run only on the server side as far as I know.

**Comment by dohomi** [comment]
You need to adjust it to your usecase. Sometimes you want that your token is available on server side as well.. sometimes not. If you are having sensitive data which is only available on the client due to some authentification, then simply don't render the content on the server just render it on the client and save the token in a localStorage.

**Comment by dohomi** [comment]
I close this issue now because it does not affect this package.
