### ISSUE TITLE
Is there a way to configure testing client (or of dynamically changing the default client)?  

### ISSUE THREAD

**Issue by alidcastano** [nuxt-community/apollo-module#75]
I know that you can configure multiple clients, but you have to use them differently too (e.g. apollo.clients.defaultClient), so that wouldn't work well for testing.

How are nuxt-apollo users running e2e tests? 

The best approach I've been able to consider is dynamically setting all clients to fetch requests from a mock server. 

@bjunc  I saw that you opened a PR for multiple clients so maybe you have some thoughts on this

**Comment by bjunc** [comment]
If you're using Apollo for request/response (not subscriptions), then testing is basically similar to how axios/REST would be.  Which is to say, similar techniques/strategies would apply.  Mock servers, stubbing, etc..

Personally, I like my e2e to be as close to an actual request/response as possible (even as far as NightWatch/TestCafe/etc, but that's not 100% necessary in my opinion).  I use mocks / stubs when testing _just_ the front-end.

For instance, I use Vue's store library (Vuex).  My tests set a JWT on the Apollo client config (I don't use a different Apollo client, I just set different auth tokens), then fire the query/mutation store actions, which hit the actual API (but which is using a test db).

_I also test the API and front-end in isolation, but that's not e2e._

For testing just the front-end, you have a few options. You could create a `test` Apollo client that had a baked in mock server by using a custom `link`.  For instance, swap out the `HttpLink` with a custom one that returns mock data.  Other mock strategies apply as well, of course.  Since you're testing the API calls in isolation, it should be fine to call the `test` client explicitly.

There's also the option of the `split` functionality baked into Apollo 2.  If running in test mode, your `client` config could have a split that uses a different `uri`, different auth token, or different `HttpLink` all-together (per above).

Another testing trick that I use that isn't e2e (but pretty cool) is that I use the [`eslint-plugin-graphql`](https://github.com/apollographql/eslint-plugin-graphql) to compare my front-end query/mutations against the API's introspection results.  You can write tests against that, or simply let eslint do its thing.

Hope that helps.

**Comment by alidcastano** [comment]
Thanks for the detailed response. 

I'd prefer not using an actual API which is why testing is a bit more difficult.

I had more of a mock server in mind. I had tried using nuxt server middleware to return the mock data but ran into a few problems. I didn't consider using an apollo link (and possibly the split functionality) but that definitely seems like the best approach. Thank for pointing me in the right direction.
