### ISSUE TITLE
Use cookie as a variable for Query in Nuxt 

### ISSUE THREAD

**Issue by gijo-varghese** [nuxt-community/apollo-module#77]
I'm using https://github.com/S64/vue-universal-cookies to use cookies on both server side and client side. This library works perfectly. However if I use it as a variable in the query, it doesn't work. Any idea?

```
<template>
 <div>
  {{ $cookies.get('customerId') }} // this works
 </div>
</template>
<script>
import CUSTOMER from "~/graphql/queries/CUSTOMER.gql";

export default {
created() {
  console.log(this.$cookies.get('customerId)) // this works on both server and client
},
  apollo: {
    customer: {
      query: CUSTOMER,
      prefetch: true,
      variables(){
        return {
         customerId: this.$cookies.get('customerId) // this doesn't work
        }
      }
   }
 }
}
```

**Comment by dohomi** [comment]
@gijo-varghese I don't use the vue-universal-cookies module. But one take is: 
instead of doing prefetch:true you should try to pass your $cookies argument to the app scope of Nuxt and do something like:
```
      prefetch: ({ app }) => {
      const customerId = app.$cookies.get('customerId') // => this is totally not tested but what you should try to do, adding cookies to the app scope  
      return {
          customerId
        }
      },
```
The reason why its not working its the prefetch:true argument as far as I remember. Because on SSR there is no `this` context in prefetch that is why you need to be careful when you use it. Hope this helps you out to solve your issue

**Comment by gijo-varghese** [comment]
Ok. let me try that

**Comment by dohomi** [comment]
will close this issue due to inactivity @gijo-varghese feel free to re-open if you still have problems

**Comment by gijo-varghese** [comment]
@dohomi this one finally worked: https://github.com/Akryum/vue-apollo/issues/227

Can you pls take a look

**Comment by dohomi** [comment]
@gijo-varghese looking good to me.
